version: "3.7"

services:
  app:
    restart: always
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/twitter
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8080:8080
    container_name: twitter

  db:
    image: dbreedt/postgres-11-postgis
    ports:
      - 5432:5432
    volumes:
      - ./storage/postgresql:/var/lib/postgresql
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter
    container_name: twitter_db